woowacourse-teams/2024-pengcook

.github/workflows/deploy.yml
Dockerfile

:sparkles: implement CI/CD workflow with Github Actions and Docker

---

android/app/build.gradle.kts
android/app/src/main/java/net/pengcook/android/MainActivity.kt
android/app/src/main/java/net/pengcook/android/MainFragment.kt
android/app/src/main/res/layout/activity_main.xml
android/app/src/main/res/layout/fragment_main.xml
android/app/src/main/res/navigation/nav_graph_main.xml
android/app/src/main/res/values/strings.xml

- implement android main navigation

:sparkles: add main navigation component

---

backend/src/main/java/net/pengcook/category/exception/CategoryException.java
backend/src/main/java/net/pengcook/exception/DomainException.java
backend/src/main/java/net/pengcook/exception/GlobalExceptionHandler.java
backend/src/main/java/net/pengcook/ingredient/exception/IngredientException.java
backend/src/main/java/net/pengcook/recipe/exception/RecipeException.java
backend/src/main/java/net/pengcook/user/exception/UserException.java

`@Valid` 과 `@Validated` 를 쓰면 아래 두 가지 예외가 발생할 수 있다.
- MethodArgumentNotValidException
- ConstraintViolationException
사용자의 요청인 DTO 에서 검증을 실패하면 발생하며 부모 구조는 BindException > Exception 이므로 GlobalExceptionHandler 에서는 잡히지 않고 아래와 같은 폼으로 응답을 자동으로 만들어줌
```json
{
"timestamp": "2024-07-22T12:34:56.789+00:00",
"status": 400,
"error": "Bad Request",
"message": "Validation failed for object='userDTO'. Error count: 2",
"errors": [
{
"object": "userDTO",
"field": "username",
"rejectedValue": "",
"message": "Username is mandatory"
},
{
"object": "userDTO",
"field": "password",
"rejectedValue": "",
"message": "Password is mandatory"
}
]
}
```
서비스 계층에서 객체 제약 조건이 위배된 경우 발생하며 부모 구조는 RuntimeException > Exception 이므로 GlobalExceptionHandler 에서 잡히고 클라이언트는 해당 정보를 볼 수 없고, 서버 내부 객체에서 문제가 생긴 것이므로 로그를 확인하여 오류를 해결해 나갈 수 …

:sparkles: setup basic exception handling

---

.github/workflows/be-ci.yaml
backend/build.gradle

`be/dev` 로 향하는 PR 작성 시 jacoco를 통한 커버리지 테스트를 돌린 후 결과를 comment 로 달아줍니다.

✨ configure continuous integration

---

.github/workflows/be-cd.yaml

배포 쪽 CD 작용할 때 빌드 하는 동안 test job 실행 시 jasypt password 가 없어서 테스트가 터지는 버그를 수정하였습니다.
해당 job 에서 env attribute를 추가하여 해결하였습니다.

🐛 fix build when deploying

---

android/app/src/main/java/net/pengcook/android/data/datasource/SearchPagingSource.kt
android/app/src/main/java/net/pengcook/android/data/model/SearchData.kt
android/app/src/main/java/net/pengcook/android/presentation/search/SearchAdapter.kt
android/app/src/main/java/net/pengcook/android/presentation/search/SearchFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/search/SearchViewModel.kt
android/app/src/main/res/drawable/ic_search_24.xml
android/app/src/main/res/layout/fragment_search.xml
android/app/src/main/res/layout/item_appbar_search.xml
android/app/src/main/res/layout/item_appbar_with_action.xml
android/app/src/main/res/layout/item_search_bar.xml
android/app/src/main/res/layout/item_search_image.xml
android/app/src/main/res/navigation/nav_graph.xml
android/app/src/main/res/values/strings.xml

* implement search layout
* component

✨ implement search layout

---

backend/build.gradle
backend/src/main/java/net/pengcook/authentication/controller/LoginController.java
backend/src/main/java/net/pengcook/authentication/dto/GoogleLoginRequest.java
backend/src/main/java/net/pengcook/authentication/dto/GoogleSignUpRequest.java
backend/src/main/java/net/pengcook/exception/GlobalExceptionHandler.java

#80 
스프링 MVC에서 발생하는 예외를 잡아줬습니다.
대표적으로 response dto에서 @Valid 어노테이션과 @NotNull @NotBlack 으로 검증하는 것들에 대한 예외를 잘 잡아줍니다.
백앤드 팀원들에게 모두 공유하는게 좋아보여서 모두 테그합니다.
혹시 바로 사용하고 싶으시면 알아서 머지 해주셔도 됩니다.

✨ spring MVC Exception Handling

---

android/app/src/main/java/net/pengcook/android/data/datasource/CategoryFeedPagingSource.kt
android/app/src/main/java/net/pengcook/android/presentation/category/Category.kt
android/app/src/main/java/net/pengcook/android/presentation/category/CategoryEventListener.kt
android/app/src/main/java/net/pengcook/android/presentation/category/CategoryFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/category/CategoryViewModel.kt
android/app/src/main/java/net/pengcook/android/presentation/category/list/CategoryFeedListAdapter.kt
android/app/src/main/java/net/pengcook/android/presentation/category/list/CategoryFeedListFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/category/list/CategoryFeedListUiEvent.kt
android/app/src/main/java/net/pengcook/android/presentation/category/list/CategoryFeedListViewModel.kt
android/app/src/main/java/net/pengcook/android/presentation/category/list/CategoryFeedListViewModelFactory.kt
android/app/src/main/java/net/pengcook/android/presentation/search/SearchFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/signup/SignUpFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/signup/SignUpViewModel.kt
android/app/src/main/res/layout/fragment_category_feed_list.xml
android/app/src/main/res/layout/item_category.xml
android/app/src/main/res/navigation/nav_graph.xml

* implement category screen to server
* CategoryFragment
* CategoryFeedListFragment

✨ connect category screen to server via API

---

backend/src/test/java/net/pengcook/user/controller/UserControllerTest.java

문서에 Parameters 가 출력되지 않던 버그를 수정했습니다.

:bug: fix username check api docs

---

backend/src/main/java/net/pengcook/image/controller/S3Controller.java
backend/src/main/java/net/pengcook/image/dto/PresignedUrlResponse.java
backend/src/main/java/net/pengcook/image/service/S3ClientService.java
backend/src/main/resources/application-dev.yaml
backend/src/main/resources/application-local.yaml
backend/src/main/resources/application-test.yaml
backend/src/test/java/net/pengcook/image/controller/S3ControllerTest.java
backend/src/test/java/net/pengcook/image/service/S3ClientServiceTest.java

- presigned url 요청 메서드, 이미지 조회 url 요청 매서드 테스트 코드 추가.
- 매개변수 명 keyName -> imageName 수정.
- yaml파일 내 cloudfront-url을 cloudfront 대체도메인으로 수정.
- PresignedUrlResponse의 필드 타입 수정.

✅ test code for Image

---

backend/src/main/java/net/pengcook/like/controller/RecipeLikeController.java
backend/src/main/java/net/pengcook/like/domain/RecipeLike.java
backend/src/main/java/net/pengcook/like/dto/RecipeLikeRequest.java
backend/src/main/java/net/pengcook/like/dto/RecipeLikeResponse.java
backend/src/main/java/net/pengcook/like/exception/RecipeLikeException.java
backend/src/main/java/net/pengcook/like/exception/RecipeNotFoundException.java
backend/src/main/java/net/pengcook/like/exception/UserNotFoundException.java
backend/src/main/java/net/pengcook/like/repository/RecipeLikeRepository.java
backend/src/main/java/net/pengcook/like/service/RecipeLikeService.java
backend/src/main/java/net/pengcook/recipe/domain/Recipe.java
backend/src/test/java/net/pengcook/like/controller/RecipeLikeControllerTest.java
backend/src/test/java/net/pengcook/like/service/RecipeLikeServiceTest.java
backend/src/test/resources/data/like.sql

아래 2개의 API 를 구현하였습니다.
- `GET` `/api/likes/{recipeId}`
- `POST` `/api/likes/{recipeId}`
간단한 `CRUD` 작업 정도여서 마음껏 피드백 부탁드립니다!

✨ like recipe and unlike

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/net/pengcook/android/data/remote/api/AuthorizationService.kt
android/app/src/main/java/net/pengcook/android/data/remote/api/FeedService.kt
android/app/src/main/java/net/pengcook/android/data/remote/api/MakingRecipeService.kt
android/app/src/main/java/net/pengcook/android/data/remote/api/StepMakingService.kt
android/app/src/main/res/xml/network_security_config.xml

* remove endpoint prefix of services
* add koreafood for fetching http domain images
* alter endpoint of fetching recipes by categories

♻ remove endpoint prefix

---

.github/workflows/be-cd.yaml

185 PR이 머지가 되었는데 CD 스크립트를 PR 타겟에만 쓸 수 있는

:bug: change field to ref

---

backend/src/main/java/net/pengcook/recipe/domain/RecipeStep.java
backend/src/main/java/net/pengcook/recipe/service/RecipeService.java
backend/src/test/java/net/pengcook/recipe/controller/RecipeControllerTest.java
backend/src/test/java/net/pengcook/recipe/service/RecipeServiceTest.java

- 레시피 스텝 등록 시 `이전 단계 레시피 스텝이 없으면 예외 발생`
- 생성 요청과 동일한 레시피 Id, 레시피 스텝 sequence가 존재하면 `기존에 존재하는 데이터를 새로운 데이터로 변경`

✨ update recipe step

---

android/app/build.gradle.kts
android/app/src/main/java/net/pengcook/android/di/DefaultAppModule.kt
android/app/src/main/java/net/pengcook/android/presentation/core/util/AnalyticsLogging.kt
android/app/src/main/java/net/pengcook/android/presentation/detail/DetailRecipeFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/home/HomeFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/making/RecipeMakingFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/making/step/StepMakingFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/onboarding/OnboardingFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/profile/ProfileFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/search/SearchFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/setting/SettingFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/signup/SignUpFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/step/RecipeStepFragment.kt
android/app/src/main/res/navigation/nav_graph.xml
android/app/src/test/java/net/pengcook/android/data/repository/making/FakeRecipeStepMakingRepository.kt
android/build.gradle.kts

✨ Logging Firebase Analytics, Crashlytics

---

backend/src/test/java/net/pengcook/authentication/controller/LoginControllerTest.java
backend/src/test/java/net/pengcook/comment/controller/CommentControllerTest.java
backend/src/test/java/net/pengcook/like/controller/RecipeLikeControllerTest.java
backend/src/test/java/net/pengcook/recipe/controller/RecipeControllerTest.java
backend/src/test/java/net/pengcook/user/controller/UserControllerTest.java

swagger에서 잘못된 summary로 조회되어 이를 삭제하고 성공 케이스에서 summary와 desciption을 가져오도록 수정했습니다.
자잘한 테스트 관련 수정사항을 반영했습니다.

♻️ change comment restdocs api summary

---

backend/src/main/java/net/pengcook/authentication/dto/GoogleSignUpRequest.java
backend/src/main/java/net/pengcook/authentication/service/LoginService.java
backend/src/main/java/net/pengcook/user/dto/UpdateProfileRequest.java
backend/src/test/java/net/pengcook/authentication/controller/LoginControllerTest.java
backend/src/test/java/net/pengcook/authentication/service/LoginServiceTest.java

GoogleSignUpRequest에 사진 필드 추가
null 입력받을 시 기본 이미지가 들어갑니다.

✨ add image field to GoogleSignUpRequest

---

backend/src/main/java/net/pengcook/category/repository/CategoryRecipeRepository.java
backend/src/main/java/net/pengcook/category/service/CategoryService.java
backend/src/test/java/net/pengcook/category/service/CategoryServiceTest.java

특정 레시피에 해당하는 레시피별 카테고리 정보를 지웁니다.

:sparkles: delete categoryRecipe by recipe

---

backend/src/main/java/net/pengcook/comment/controller/CommentController.java
backend/src/main/java/net/pengcook/comment/exception/UnauthorizedDeletionException.java
backend/src/main/java/net/pengcook/comment/service/CommentService.java
backend/src/test/java/net/pengcook/comment/controller/CommentControllerTest.java
backend/src/test/java/net/pengcook/comment/service/CommentServiceTest.java

댓글 아이디를 받아 삭제합니다.
댓글이 존재하지 않거나, 내 댓글이 아닌 경우 예외가 발생합니다.

:sparkles: delete comment by commentId

---

android/app/build.gradle.kts
android/app/src/main/java/net/pengcook/android/data/datasource/SearchPagingSource.kt
android/app/src/main/java/net/pengcook/android/data/model/SearchData.kt
android/app/src/main/java/net/pengcook/android/presentation/search/SearchActionListener.kt
android/app/src/main/java/net/pengcook/android/presentation/search/SearchAdapter.kt
android/app/src/main/java/net/pengcook/android/presentation/search/SearchEventListener.kt
android/app/src/main/java/net/pengcook/android/presentation/search/SearchFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/search/SearchUiEvent.kt
android/app/src/main/java/net/pengcook/android/presentation/search/SearchViewModel.kt
android/app/src/main/java/net/pengcook/android/presentation/search/SearchViewModelFactory.kt
android/app/src/main/res/layout/fragment_search.xml
android/app/src/main/res/layout/item_appbar_search.xml
android/app/src/main/res/layout/item_search_image.xml
android/app/src/main/res/navigation/nav_graph.xml
android/app/src/main/res/values/strings.xml
android/app/src/main/res/xml/network_security_config.xml
android/app/src/test/java/net/pengcook/android/data/datasource/SearchPagingSourceTest.kt
android/app/src/test/java/net/pengcook/android/data/repository/feed/FakeFeedRepository.kt
android/app/src/test/java/net/pengcook/android/presentation/search/SearchViewModelTest.kt

* apply filtering data by keyword
* changed the PagingData 
* `LiveData -> Flow` for filtering paging data

✨ implement search screen server connection via api
