woowacourse-teams/2024-pengcook

backend/src/main/java/net/pengcook/category/domain/Category.java
backend/src/main/java/net/pengcook/category/domain/CategoryRecipe.java
backend/src/main/java/net/pengcook/category/repository/CategoryRecipeRepository.java
backend/src/main/java/net/pengcook/category/repository/CategoryRepository.java
backend/src/main/java/net/pengcook/category/service/CategoryService.java
backend/src/test/java/net/pengcook/category/service/CategoryServiceTest.java
backend/src/test/resources/data/category.sql

카테고리명을 List로 받아 각각의 String에 대해 저장 작업을 합니다.
카테고리 하나의 저장 과정은 다음과 같습니다.
먼저 그 String이 카테고리 테이블에 있는지 확인합니다.
있다면 그 카테고리를 가져오고, 없다면 String을 카테고리 테이블에 저장한 후 가져옵니다.
그리고 레시피-카테고리 중간 테이블에 저장합니다.

✨ save categories of recipe

---

backend/src/main/java/net/pengcook/authentication/exception/AuthenticationException.java
backend/src/main/java/net/pengcook/authentication/exception/AuthorizationHeaderException.java
backend/src/main/java/net/pengcook/authentication/exception/DuplicationException.java
backend/src/main/java/net/pengcook/authentication/exception/FirebaseTokenException.java
backend/src/main/java/net/pengcook/authentication/exception/JwtTokenException.java
backend/src/main/java/net/pengcook/authentication/service/LoginService.java
backend/src/main/java/net/pengcook/authentication/util/JwtTokenManager.java
backend/src/main/java/net/pengcook/authentication/util/TokenExtractor.java
backend/src/main/java/net/pengcook/category/exception/CategoryException.java
backend/src/main/java/net/pengcook/exception/DomainException.java
backend/src/main/java/net/pengcook/exception/GlobalExceptionHandler.java
backend/src/main/java/net/pengcook/ingredient/exception/IngredientException.java
backend/src/main/java/net/pengcook/recipe/exception/RecipeException.java
backend/src/main/java/net/pengcook/user/exception/UserException.java
backend/src/test/java/net/pengcook/authentication/controller/LoginControllerTest.java
backend/src/test/java/net/pengcook/authentication/service/LoginServiceTest.java
backend/src/test/java/net/pengcook/authentication/util/JwtTokenManagerTest.java
backend/src/test/java/net/pengcook/authentication/util/TokenExtractorTest.java

- 커스텀 예외에 status를 추가했습니다.
- 각 요청의 예외마다 다른 status를 응답하기위해 handleDomainException 메서드에서 ResponseEntity를 리턴했습니다. 
- 일관성을 위해 handleException 메서드도 ResponseEntity를 리턴하게 했습니다.

✨ Seperate DomainException by response status

---

backend/src/main/java/net/pengcook/category/controller/CategoryController.java
backend/src/main/java/net/pengcook/category/dto/RecipeOfCategoryRequest.java
backend/src/main/java/net/pengcook/category/repository/CategoryRecipeRepository.java
backend/src/main/java/net/pengcook/category/service/CategoryService.java
backend/src/test/java/net/pengcook/category/controller/CategoryControllerTest.java
backend/src/test/java/net/pengcook/category/repository/CategoryRecipeRepositoryTest.java
backend/src/test/java/net/pengcook/category/service/CategoryServiceTest.java
backend/src/test/resources/data/category.sql

카테고리명과 페이지 번호, 개수를 전달받아 카테고리 레시피 테이블에서 그 카테고리명을 갖는 레시피 아이디를 찾습니다.
이후 엘라(recipe)의 서비스에 있는 메서드를 활용해 그 아이디의 레시피를 조회합니다.

:sparkles: get recipes by category

---

backend/src/main/java/net/pengcook/recipe/controller/RecipeController.java
backend/src/main/java/net/pengcook/recipe/domain/Recipe.java
backend/src/main/java/net/pengcook/recipe/domain/RecipeStep.java
backend/src/main/java/net/pengcook/recipe/dto/MainRecipeRequest.java
backend/src/main/java/net/pengcook/recipe/dto/RecipeStepResponse.java
backend/src/main/java/net/pengcook/recipe/repository/RecipeStepRepository.java
backend/src/main/java/net/pengcook/recipe/service/RecipeService.java
backend/src/test/java/net/pengcook/recipe/controller/RecipeControllerTest.java
backend/src/test/java/net/pengcook/recipe/service/RecipeServiceTest.java
backend/src/test/resources/data/recipe.sql

```/api/recipes/{id}/steps```
```/api/recipes```
- 레시피 Id를 통한 레시피 검색이 추가될 것을 고려해서, 스텝 조회 엔드포인트를 특정 레시피의 steps를 가져온다는 흐름으로 설정했습니다.
- 메인페이지에서 레시피 목록 조회시 페이지 정보를 body로 받던 것을 RequestParam으로 받아오도록 수정했습니다.
(이 부분은 별도 이슈로 관리되어야 했던 것 같은데 리팩토링 하다보니 같이 작업하게 됐습니다. 다음번에는 분리하겠습니다!)

✨ implement recipe steps retrieval

---

backend/src/main/java/net/pengcook/ingredient/domain/Ingredient.java
backend/src/main/java/net/pengcook/ingredient/domain/IngredientRecipe.java
backend/src/main/java/net/pengcook/ingredient/domain/IngredientSubstitution.java
backend/src/main/java/net/pengcook/ingredient/dto/IngredientCreateRequest.java
backend/src/main/java/net/pengcook/ingredient/exception/InvalidNameException.java
backend/src/main/java/net/pengcook/ingredient/repository/IngredientRecipeRepository.java
backend/src/main/java/net/pengcook/ingredient/repository/IngredientRepository.java
backend/src/main/java/net/pengcook/ingredient/repository/IngredientSubstitutionRepository.java
backend/src/main/java/net/pengcook/ingredient/service/IngredientRecipeService.java
backend/src/main/java/net/pengcook/ingredient/service/IngredientService.java
backend/src/main/java/net/pengcook/ingredient/service/IngredientSubstitutionService.java
backend/src/test/java/net/pengcook/ingredient/dto/IngredientCreateRequestTest.java
backend/src/test/java/net/pengcook/ingredient/service/IngredientServiceTest.java
backend/src/test/resources/data/ingredient.sql

`IngredientService`의 `register` 메서드를 통해 재료 등록을 진행합니다.
1. Ingredient 등록
2. IngredientRecipe 등록
3. 재료가 '대체 가능'한 상태라면 IngredientSubstitution 등록 
재료 이름 공백/null, 중복 
개별 재료에 대한 대체 재료 이름 공백/null, 중복
- #24 
- #26

✨ implement ingredient registration

---

backend/.gitignore
backend/build.gradle
backend/src/main/resources/application.yaml
backend/src/test/java/net/pengcook/RestDocsSetting.java
backend/src/test/java/net/pengcook/category/controller/CategoryControllerTest.java

build.gradle에 의존성과 task를 추가해 rest docs와 swagger ui를 도입했습니다.
사용 방법은 다음과 같습니다.
1. 컨트롤러 E2E 테스트를 `RestDocsSetting`을 상속받게 변경합니다.
2. 각 테스트에 rest docs에서 요구하는 요소를 추가합니다.
- `given`에 파라미터로 `spec`을 넣습니다. `spec`은 `RestDocsSetting`에 이미 정의되어있으니 가져다 쓰시면 됩니다.
- `given.log.all` 뒤에 `filter` 메서드를 추가합니다. 형태는 `CategoryControllerTest`를 보시면 이해가 빠를 겁니다.
- 뭘 추가해야할지 모르시겠다면... 불러주세요. 함께 공부합시다.
4. 이후 Gradle bootJar을 실행하면 openapi3.yaml 이 resources/static 으로 들어옵니다.
5. [http://localhost:8080/swagger-ui/index.html](http://localhost:8080/swagger-ui/index.html)로 접속하면 기존의 swagger로 만든 api 문서와 동일한 결과를 보실 수 있습니다.
궁금한 부분이 있다면 질문 주세요.
special thanks to 새양 입니다.

✨ add rest docs and swagger ui for category test

---

backend/src/main/java/net/pengcook/authentication/config/LoginUserArgumentResolverConfig.java
backend/src/main/java/net/pengcook/authentication/service/LoginService.java
backend/src/main/java/net/pengcook/user/controller/UserController.java
backend/src/main/java/net/pengcook/user/repository/UserRepository.java
backend/src/test/java/net/pengcook/user/controller/UserControllerTest.java

잘못 설계했던 api를 변경했습니다.
기존 : `api/user/{{id}}`
변경 : `api/user/me`

♻️ change user api

---

.github/workflows/be-cd.yaml
.github/workflows/be-ci.yaml
backend/build.gradle

API docs가 추가되며 cd가 실행될 때 `gradle task` 가 종속적인 실행 때문에 테스트가 실패하던 버그 발생
`copyOasToSwagger task` 를 cd 에서 독립적으로 실행함으로써 문제를 해결

🐛 problem on copyOasToSwagger gradle task when cd

---

backend/src/test/java/net/pengcook/authentication/annotation/WithLoginUser.java
backend/src/test/java/net/pengcook/authentication/annotation/WithLoginUserTest.java
backend/src/test/java/net/pengcook/authentication/extension/LoginExtension.java

E2E 테스트시 로그인 테스트를 쉽게 하기위해 어노테이션을 만들었습니다.
1. 사용할 ControllerTest 단에 `@WithLoginUserTest`을 붙여줍니다.
```java
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
@WithLoginUserTest
@Sql("/data/users.sql")
class UserControllerTest {
...
```
2. 사용할 메서드에  `@WithLoginUser`를 붙여줍니다.
- 인자 없이 전달하면 기본값으로 `tester@pengcook.net` 이메일을 가지는 테스트 유저가 생성되고 로그인됨
- (email, username, nickname, image, birth, region)을 설정할 수 있음. `data.sql`에 이미 있는 email의 유저를 만들면 다시 생성되지 않고 기존 유저를 찾아옴.
- 가짜 로그인이 아니라 실제로 userRepository에 저장됨. 테스트중 유저가 필요하면 userRepository.findByEmail을 통해 조회 가능
```java
@Test
@WithLoginUser(email = "loki@pengcook.net")
@DisplayName("사용자의 정보를 조회한다.")
void getUserProfile() {
long id = 1L;
UserResponse expected = new UserResponse(
id,
"loki@pengcook.net",
"loki",
"로키",
"loki.jpg",
LocalDate.of(1999, 8, …
```

✨  create login test annotation

---

backend/src/test/java/net/pengcook/recipe/controller/RecipeControllerTest.java

✨ add recipe retrieval docs

---

backend/src/main/java/net/pengcook/authentication/dto/GoogleSignUpRequest.java
backend/src/main/java/net/pengcook/authentication/dto/GoogleSignUpResponse.java
backend/src/main/java/net/pengcook/authentication/service/LoginService.java
backend/src/main/java/net/pengcook/user/domain/User.java
backend/src/main/java/net/pengcook/user/dto/UserResponse.java
backend/src/test/java/net/pengcook/authentication/annotation/WithLoginUser.java
backend/src/test/java/net/pengcook/authentication/controller/LoginControllerTest.java
backend/src/test/java/net/pengcook/authentication/extension/LoginExtension.java
backend/src/test/java/net/pengcook/authentication/service/LoginServiceTest.java
backend/src/test/java/net/pengcook/category/service/CategoryServiceTest.java
backend/src/test/java/net/pengcook/user/controller/UserControllerTest.java
backend/src/test/java/net/pengcook/user/service/UserServiceTest.java
backend/src/test/resources/data/category.sql
backend/src/test/resources/data/ingredient.sql
backend/src/test/resources/data/recipe.sql
backend/src/test/resources/data/users.sql

:fire: remove birthday code

---

backend/build.gradle
backend/src/main/resources/docker-compose-dev.yaml
backend/src/main/resources/docker-compose-local.yaml
backend/src/main/resources/logback-spring.xml

https://www.baeldung.com/spring-boot-loki-grafana-logging
해당 사이트를 참고하여 그라파나와 로키를 추가하여 로깅에 대한 부분만 모니터링을 추가하였습니다.
매트릭에 대한 정보는 추후 새로운 이슈에서 추가할 것이며 아마 프로메테우스를 사용하여 그라파나로 연결할 것 같습니다.
- **Grafana** 데이터 시각화
- **Loki** 로그 데이터 수집
- **Prometheus** 매트릭 데이터 수집
Spring Boot 는 자신에게 발생하는 로그들을  Loki에게 API 요청을 하여 데이터를 추가합니다.
추가된 데이터를 Grafana 가 Loki에게서 읽은 뒤 `label` 에 따라 검색할 수 있도록 해줍니다.

✨ add log monitoring dashboard

---

backend/build.gradle
backend/src/main/resources/application-dev.yaml
backend/src/main/resources/application-local.yaml
backend/src/main/resources/docker-compose-dev.yaml
backend/src/main/resources/docker-compose-local.yaml

- 기존 `Grafana` 와 `Loki` 의 로그 모니터링 도구에 `Prometheus` 라는 매트릭 수집기를 추가함
- `Prometheus` 컨테이너는 `Spring Boot` 인 `app` 컨테이너로 15초 마다 `/actuator/prometheus` 로 `GET` 요청을 하여 정보를 들고와 데이터를 수집함
- `Grafana` 에서는 `Prometheus` 를 데이터 소스로 설정하여 매트릭 데이터를 시각화 하여 보여줌

✨ add metric monitoring dashboard

---

backend/src/main/resources/logback-spring.xml

`Loki` 적용 이후 콘솔에 로그가 보이지 않던 버그를 수정하였습니다.
https://stackoverflow.com/questions/30571319/spring-boot-logging-pattern
위 링크를 참고하여 `Spring Boot Logback` 의 기본 패턴을 그대로 사용할 수 있었습니다!

🐛 show log on console

---

backend/src/main/resources/docker-compose-dev.yaml
backend/src/main/resources/docker-compose-local.yaml

- `Grafana` `Loki` `Promethesu` 3종 세트를 추가하며 각 컨테이너에 대해 `restart` 옵션을 주지 않아 `EC2` 를 재부팅 하면 모니터링 컨테이너는 재실행 되지 않던 것을 `restart` 옵션을 추가함으로써 작동하도록 변경하였습니다.
- 또한 `Grafana` 컨테이너가 재부팅 되면 데이터가 사라져 `Contact Points` 에 `Discord Webhook` 설정 등이 사라지는 점을 `volume` 을 추가함으로써 해결하였습니다.

:zap: set restart options on containers

---

backend/src/main/java/net/pengcook/recipe/controller/RecipeController.java
backend/src/main/java/net/pengcook/recipe/domain/Recipe.java
backend/src/main/java/net/pengcook/recipe/domain/RecipeStep.java
backend/src/main/java/net/pengcook/recipe/dto/RecipeRequest.java
backend/src/main/java/net/pengcook/recipe/dto/RecipeResponse.java
backend/src/main/java/net/pengcook/recipe/dto/RecipeStepRequest.java
backend/src/main/java/net/pengcook/recipe/exception/NotFoundException.java
backend/src/main/java/net/pengcook/recipe/repository/RecipeStepRepository.java
backend/src/main/java/net/pengcook/recipe/service/RecipeService.java
backend/src/test/java/net/pengcook/category/service/CategoryServiceTest.java
backend/src/test/java/net/pengcook/recipe/controller/RecipeControllerTest.java
backend/src/test/java/net/pengcook/recipe/service/RecipeServiceTest.java

(1) POST `/api/recipes`
(2) POST `/api/recipes/{recipeId}/steps`
(3) GET `/api/recipes/{recipeId}/steps/{sequence}`
- 레시피 생성 흐름은 다음과 같습니다.
Recipe 생성 요청(1) -> 생성된 Recipe의 id 응답 -> Recipe id와 함께 각 Recipe Step 생성 요청(2) -> 생성된 Recipe Step 정보 응답
레시피 생성 중 레시피 스텝 전/후로 이동하기 위해 Recipe id, sequence로 Step 조회하는 API(3) 가 추가되었습니다.
- 필드 수정
RecipeStep에 해당 Step의 소요시간 필드 추가
---
레시피 생성 하나의 이슈인데 레시피 생성을 위한 단계가 많아 코드 변경사항이 조금 있습니다.
`레시피 생성`, `레시피 스텝 생성`, `레시피의 스텝 조회` 각각의 흐름을 따라가며 보시면 좀 더 보기 편하실 것 같습니다.
중복 sequence 검증 등의 예외 처리는 되어있지 않습니다. 참고 부탁드리며 편하게 피드백 부탁드립니다!!! 🙇🏻‍♀️

✨ implement recipe and recipe steps creation

---

backend/src/main/java/net/pengcook/comment/controller/CommentController.java
backend/src/main/java/net/pengcook/comment/domain/Comment.java
backend/src/main/java/net/pengcook/comment/dto/CommentOfRecipeResponse.java
backend/src/main/java/net/pengcook/comment/dto/CommentResponse.java
backend/src/main/java/net/pengcook/comment/repository/CommentRepository.java
backend/src/main/java/net/pengcook/comment/service/CommentService.java
backend/src/test/java/net/pengcook/comment/controller/CommentControllerTest.java
backend/src/test/java/net/pengcook/comment/service/CommentServiceTest.java
backend/src/test/resources/data/comment.sql

레시피의 아이디를 받아 댓글을 조회합니다.
이 때 로그인한 유저의 댓글인지를 확인할 수 있어야 삭제 버튼을 노출시킬 수 있어, mine이라는 필드가 존재합니다.
`comment.getUser().getId() == userInfo.getId()` 부분은 나중에 UserInfo로 옮기면 좋을 것 같네요!

:sparkles: read comments of recipe

---

backend/src/main/java/net/pengcook/comment/controller/CommentController.java
backend/src/main/java/net/pengcook/comment/domain/Comment.java
backend/src/main/java/net/pengcook/comment/dto/CreateCommentRequest.java
backend/src/main/java/net/pengcook/comment/exception/CommentException.java
backend/src/main/java/net/pengcook/comment/exception/NotFoundException.java
backend/src/main/java/net/pengcook/comment/service/CommentService.java
backend/src/test/java/net/pengcook/comment/controller/CommentControllerTest.java
backend/src/test/java/net/pengcook/comment/service/CommentServiceTest.java

✨ create comment on recipe

---

backend/src/main/java/net/pengcook/authentication/config/LoginUserArgumentResolverConfig.java
backend/src/main/java/net/pengcook/authentication/controller/LoginController.java
backend/src/main/java/net/pengcook/authentication/interceptor/UserInfoInterceptor.java
backend/src/main/java/net/pengcook/authentication/resolver/LoginUserArgumentResolver.java
backend/src/main/java/net/pengcook/authentication/service/LoginService.java
backend/src/main/java/net/pengcook/recipe/dto/RecipeDataResponse.java
backend/src/main/java/net/pengcook/user/aop/BlockedUserFilterAspect.java
backend/src/main/java/net/pengcook/user/controller/UserController.java
backend/src/main/java/net/pengcook/user/domain/AuthorAble.java
backend/src/main/java/net/pengcook/user/domain/BlockedUserGroup.java
backend/src/main/java/net/pengcook/user/domain/User.java
backend/src/main/java/net/pengcook/user/domain/UserBlock.java
backend/src/main/java/net/pengcook/user/dto/UserBlockRequest.java
backend/src/main/java/net/pengcook/user/dto/UserBlockResponse.java
backend/src/main/java/net/pengcook/user/exception/BadArgumentException.java
backend/src/main/java/net/pengcook/user/exception/UserNotFoundException.java
backend/src/main/java/net/pengcook/user/repository/UserBlockRepository.java
backend/src/main/java/net/pengcook/user/service/UserService.java
backend/src/test/java/net/pengcook/authentication/controller/LoginControllerTest.java
backend/src/test/java/net/pengcook/authentication/service/LoginServiceTest.java
backend/src/test/java/net/pengcook/category/service/CategoryServiceTest.java
backend/src/test/java/net/pengcook/user/aop/BlockedUserFilterAspectTest.java
backend/src/test/java/net/pengcook/user/controller/UserControllerTest.java
backend/src/test/java/net/pengcook/user/domain/BlockedUserGroupTest.java
backend/src/test/java/net/pengcook/user/domain/UserBlockTest.java
backend/src/test/java/net/pengcook/user/service/UserServiceTest.java
backend/src/test/resources/data/blocked-user.sql
backend/src/test/resources/data/users.sql

차단한 유저의 컨텐츠를 보이지 않게 하는 기능입니다.
pr에는 사용법 위주로 설명하고 동작방식은 오프라인 코드리뷰로 설명하겠습니다.
레포지토리에서 리턴되는 클래스가 작성자 필드가 있다면 `AuthorAble`을 구현해주면 됩니다.
```java
public interface AuthorAble {
long getAuthorId();
}
```
> *예시*
>
> `RecipeRepository`의 `findRecipeData`이 `List<RecipeDataResponse>`을 리턴함
>
> ![스크린샷 2024-08-04 오후 4 07 23](https://github.com/user-attachments/assets/4dbd2f7e-0438-46ff-8cdd-a72f18c94952)
>
> RecipeDataResponse는 AuthorAble을 구현
>
> ![스크린샷 2024-08-04 오후 4 09 02](https://github.com/user-attachments/assets/566647ba-3cbb-405c-98b3-2bf92f90038c)
> 
- 요청이 들어왔을때 `HttpServletRequest`에서 사용자의 정보를 가져오고 저장하므로 실제 요청이 있어야 작동합니다. (실제 요청 또는 `RestAssured`를 이용한 테스트에서만 블럭이 됨)

✨ blocked user fillter

---

.github/workflows/be-cd.yaml
.github/workflows/be-ci.yaml

`Github Actions` 에서 워크플루가 2개 이상 작동할 때 `CI` 쪽은 크게 문제가 없을 수도 있지만 `CD` 쪽에서 이전 버전의 배포가 최신 버전을 덮어 씌운 뒤 서버에 올라가는 동시성 문제가 있음
스크립트 자체에 `concurrency` 를 추가하여 새로운 `CD Workflow` 가 실행되면 이전의 `Workflow` 는 중지되도록 스크립트를 변경

⚡ prevent to run cd concurrently

---

backend/src/main/java/net/pengcook/exception/GlobalExceptionHandler.java
backend/src/main/java/net/pengcook/like/controller/RecipeLikeController.java
backend/src/main/java/net/pengcook/like/dto/RecipeLikeRequest.java
backend/src/main/java/net/pengcook/like/dto/RecipeLikeResponse.java
backend/src/main/java/net/pengcook/like/repository/RecipeLikeRepository.java
backend/src/main/java/net/pengcook/like/service/RecipeLikeService.java
backend/src/test/java/net/pengcook/like/controller/RecipeLikeControllerTest.java
backend/src/test/java/net/pengcook/like/service/RecipeLikeServiceTest.java

- 좋아요 취소 요청이 무한으로 요청되어 좋아요가 `-n` 까지 내려가는 문제 발생
- 아래 4가지 상황을 모두 개수와 함께 테스트
- 좋아요 안한 게시글에 좋아요
- 좋아요 안한 게시글에 좋아요 취소
- 좋아요 한 게시글에 좋아요
- 좋아요 한 게시글에 좋아요 취소
- 추가로, 모든 `DomainException` 에 대해 `4xx` `Http Status Code` 임에도 불구하고 로깅을 하는 것을 `5xx` 코드에 대해서만 로깅하도록 수정하였습니다.
- 게시글 개요 조회 시 `likesCount` 가 보이기 때문에 `/likes/{recipeId}` 는 자기자신의 좋아요인지 확인하는 `API` 로 수정하였습니다.

🐛 prevent to cancel like many times

---

backend/src/main/resources/application-dev.yaml
backend/src/main/resources/application-local.yaml
backend/src/main/resources/docker-compose-dev.yaml
backend/src/main/resources/docker-compose-local.yaml

- 새로운 `CD` 가 작동되어 서버로 반영될 때 마다 `3306` 포트가 닫혀버려서 `docker-compose-dev.yaml` 파일에 `port` 속성을 추가했습니다!
- 또한 `db` 쪽 환경변수로 `timezone` 을 `TZ` 로 설정하여 db에 반영되도록 하였습니다.
- `Spring Boot` 실행 쪽에서도 현구막 블로그를 보며 컨테이너에 `TZ` 환경변수를 지정하였습니다.
- 로컬 `docker compose` 를 재시작 하여 `select now();` 쿼리를 실행하여 DB에서 현재 시간이 언제로 나오는지 체크해보았습니다.

:sparkles: change server tz and open container db port

---

backend/src/main/java/net/pengcook/recipe/controller/RecipeController.java
backend/src/main/java/net/pengcook/recipe/domain/RecipeStep.java
backend/src/main/java/net/pengcook/recipe/dto/RecipeStepRequest.java
backend/src/main/java/net/pengcook/recipe/service/RecipeService.java
backend/src/main/java/net/pengcook/recipe/service/RecipeStepService.java
backend/src/test/java/net/pengcook/recipe/service/RecipeServiceTest.java
backend/src/test/java/net/pengcook/recipe/service/RecipeStepServiceTest.java

레시피 스텝 생성 시 검증 로직 수정하였습니다. 
- 이미지 관련
(기존) 이미지에 null 값 혹은 빈 문자열을 보내면 null, " "로 저장 → (변경) 이미지를 null로 보내면 `null로 저장`, 빈 문자열 입력 불가
- 조리시간 관련
(기존) 조리시간에 null값 불가, 올바르지 않은 형태의 조리시간 보내면 500에러 발생 -> (변경) 조리시간 `null 가능`, 형태 검증 추가

♻️ modify recipe step creation validation

---

.github/issue-branch.yaml
.github/workflows/issue-automation.yaml

`issue automation` 은 `Default Branch` 에 스크립트가 있어야 동작합니다.
이제 이슈를 생성하면 해당 이슈 번호와 `Labels` 를 통해 `be/feat/213` 또는 `an/feat/214` 브랜치가 자동 생성 됩니다!
똑같이 PR 이 자동으로 생성되고 각 분야 별로 `be/dev <- be/feat/213` 또는 `an/dev <- an/feat/214` 를 향하도록 PR이 생성됩니다.
- `Branch` 는 자동으로 삭제 됩니다.
- ⚠️ 하지만 `Issue` 가 자동으로 닫히진 않더군요. 우선 이슈는 직접 `Close` 해주시길 바랍니다! 추후 자동화 가능 할 수도 있습니다.

:technologist: add issue automation

---

android/app/src/main/java/net/pengcook/android/presentation/making/step/StepMakingFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/making/step/StepMakingViewModel.kt
android/app/src/main/res/navigation/nav_graph.xml
android/app/src/test/java/net/pengcook/android/presentation/making/step/StepMakingViewModelTest.kt

🐛  navigation error
- before: navigation action of making step
- after: making step Fragment-> back press ; (navigateUp call) -> making recipe Fragment
making step Fragment -> press "X" button; -> move to "Home(Feed) Fragment
- before : when back pressed on Home Fragment, Onboarding fragment showed.
- after : when back pressed on Home Fragment, app closed.
🐛  viewmodel logic error (StepMakingViewModel)
- before : impossible to complete making recipe when it is on first step
- after: only impossible when the introduction is empty

🐛 fix navigation error and viewmodel logic errors

---

backend/src/main/java/net/pengcook/recipe/dto/PageRecipeRequest.java
backend/src/main/java/net/pengcook/recipe/repository/RecipeRepository.java
backend/src/main/java/net/pengcook/recipe/service/RecipeService.java
backend/src/test/java/net/pengcook/category/repository/CategoryRecipeRepositoryTest.java
backend/src/test/java/net/pengcook/recipe/controller/RecipeControllerTest.java
backend/src/test/java/net/pengcook/recipe/repository/RecipeRepositoryTest.java
backend/src/test/java/net/pengcook/recipe/service/RecipeServiceTest.java

`GET /recipes` 에 대해 파라미터가 필수와 옵션이 생겼습니다.
**필수** `pageNumber` `pageSize`
**옵션** `category` `keyword` `userId`
옵션은 `Nullable` 하며 해당 조건에 모두 부합하는 경우를 찾은 뒤 `Pageable` 이 적용됩니다.
카테고리별 검색, 유저아이디별 검색 API 가 더 이상 사용되지 않을 예정이라 삭제를 해야할 것 같습니다.

✨ search recipes with keywords

---

android/app/src/main/java/net/pengcook/android/data/datasource/comment/CommentDataSource.kt
android/app/src/main/java/net/pengcook/android/data/datasource/comment/DefaultCommentDataSource.kt
android/app/src/main/java/net/pengcook/android/data/datasource/comment/FakeCommentDataSource.kt
android/app/src/main/java/net/pengcook/android/data/model/comment/CommentRequest.kt
android/app/src/main/java/net/pengcook/android/data/model/comment/CommentResponse.kt
android/app/src/main/java/net/pengcook/android/data/remote/api/CommentService.kt
android/app/src/main/java/net/pengcook/android/data/repository/comment/CommentRepository.kt
android/app/src/main/java/net/pengcook/android/data/repository/comment/DefaultCommentRepository.kt
android/app/src/main/java/net/pengcook/android/data/repository/comment/FakeCommentRepository.kt
android/app/src/main/java/net/pengcook/android/di/AppModule.kt
android/app/src/main/java/net/pengcook/android/di/DefaultAppModule.kt
android/app/src/main/java/net/pengcook/android/presentation/BindingAdapters.kt
android/app/src/main/java/net/pengcook/android/presentation/comment/CommentAdapter.kt
android/app/src/main/java/net/pengcook/android/presentation/comment/CommentEventHandler.kt
android/app/src/main/java/net/pengcook/android/presentation/comment/CommentFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/comment/CommentViewHolder.kt
android/app/src/main/java/net/pengcook/android/presentation/comment/CommentViewModel.kt
android/app/src/main/java/net/pengcook/android/presentation/comment/CommentViewModelFactory.kt
android/app/src/main/java/net/pengcook/android/presentation/core/listener/ActionEventHandler.kt
android/app/src/main/java/net/pengcook/android/presentation/detail/DetailRecipeFragment.kt
android/app/src/main/java/net/pengcook/android/presentation/detail/DetailRecipeViewModel.kt
android/app/src/main/res/drawable/ic_send_24.xml
android/app/src/main/res/layout/fragment_comment.xml
android/app/src/main/res/layout/fragment_detail_recipe.xml
android/app/src/main/res/layout/item_appbar_with_right_action.xml
android/app/src/main/res/layout/item_comment.xml
android/app/src/main/res/layout/item_textfield_with_action.xml
android/app/src/main/res/navigation/nav_graph.xml
android/app/src/main/res/values/strings.xml

- Comment layout implemented
- Comment api binding implemented
- ⭕ fetch, post implemented
- ❌ delete is not yet implemented

✨ Comment layout and api binding

---

.github/workflows/an-cd.yml
android/app/build.gradle.kts

change cd pipelines
* track : alpha -> production

:rocket: deploy release v1.0.0

---

backend/src/main/java/net/pengcook/recipe/controller/RecipeController.java
backend/src/main/java/net/pengcook/recipe/domain/Recipe.java
backend/src/main/java/net/pengcook/recipe/dto/RecipeUpdateRequest.java
backend/src/main/java/net/pengcook/recipe/service/RecipeService.java
backend/src/test/java/net/pengcook/recipe/controller/RecipeControllerTest.java
backend/src/test/java/net/pengcook/recipe/service/RecipeServiceTest.java

1. 변경감지를 이용한 레시피 수정
2. 기존의 레시피 스탭들을 삭제
3. 새로운 레시피 스탭들을 생성

:sparkles: update recipe
